services:
  postgres:
    image: postgres:latest
    container_name: piebook_postgres
    environment:
      POSTGRES_DB: piebook_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: